### ISSUE TITLE
Alliance level? (suggestion)

### ISSUE THREAD

**Issue by Silly-123123** [Geuthur/aa-killstats#8]
i would like to have this on Alliance level if that is possible?

and could it be made that we can make our own criteria for the wall of shame and fame?

**Comment by Geuthur** [comment]
Hi,

1. atm it is not possible from the code.
I will look at this and at this to the upcoming features

2. I am not sure what you mean with criteria? 
normally the fame & shame shows kills and losses from each Main(Alts)

**Comment by Silly-123123** [comment]
Criteria, for example,

Hall of shame
Biggest Miner loss:
must be in a barge, or suport barge

or have a criteria
Biggest frigate loss.

we can also decided what actualy shows up on the hall of fame and shame?

Op di 6 aug 2024 om 23:20 schreef Geuthur ***@***.***>:

**Comment by Geuthur** [comment]
Ok on this level.

I will look at it, it will take time to make this possible cause i  don't have an option for setting filters for kills.

First i will make a way to Fetch Kills on Alliance Level and show them seperate.

**Comment by Silly-123123** [comment]
SOUNDS awesome :D

Op wo 7 aug 2024 om 11:16 schreef Geuthur ***@***.***>:
